<?php
return array(
  array('id' => '1','province_id' => '1','active' => '1','title' => 'آذرشهر','slug' => 'آذرشهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '2','province_id' => '1','active' => '1','title' => 'اسکو','slug' => 'اسکو','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '3','province_id' => '1','active' => '1','title' => 'اهر','slug' => 'اهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '4','province_id' => '1','active' => '1','title' => 'بستان آباد','slug' => 'بستان_آباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '5','province_id' => '1','active' => '1','title' => 'بناب','slug' => 'بناب','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '6','province_id' => '1','active' => '1','title' => 'تبریز','slug' => 'تبریز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '7','province_id' => '1','active' => '1','title' => 'جلفا','slug' => 'جلفا','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '8','province_id' => '1','active' => '1','title' => 'چاراویماق','slug' => 'چاراویماق','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '9','province_id' => '1','active' => '1','title' => 'خداآفرین','slug' => 'خداآفرین','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '10','province_id' => '1','active' => '1','title' => 'سراب','slug' => 'سراب','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '11','province_id' => '1','active' => '1','title' => 'شبستر','slug' => 'شبستر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '12','province_id' => '1','active' => '1','title' => 'عجب شیر','slug' => 'عجب_شیر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '13','province_id' => '1','active' => '1','title' => 'کلیبر','slug' => 'کلیبر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '14','province_id' => '1','active' => '1','title' => 'مراغه','slug' => 'مراغه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '15','province_id' => '1','active' => '1','title' => 'مرند','slug' => 'مرند','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '16','province_id' => '1','active' => '1','title' => 'ملکان','slug' => 'ملکان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '17','province_id' => '1','active' => '1','title' => 'میانه','slug' => 'میانه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '18','province_id' => '1','active' => '1','title' => 'ورزقان','slug' => 'ورزقان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '19','province_id' => '1','active' => '1','title' => 'هریس','slug' => 'هریس','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '20','province_id' => '1','active' => '1','title' => 'هشترود','slug' => 'هشترود','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '21','province_id' => '1','active' => '1','title' => 'هوراند','slug' => 'هوراند','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '22','province_id' => '2','active' => '1','title' => 'ارومیه','slug' => 'ارومیه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '23','province_id' => '2','active' => '1','title' => 'اشنویه','slug' => 'اشنویه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '24','province_id' => '2','active' => '1','title' => 'بوکان','slug' => 'بوکان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '25','province_id' => '2','active' => '1','title' => 'پلدشت','slug' => 'پلدشت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '26','province_id' => '2','active' => '1','title' => 'پیرانشهر','slug' => 'پیرانشهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '27','province_id' => '2','active' => '1','title' => 'تکاب','slug' => 'تکاب','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '28','province_id' => '2','active' => '1','title' => 'چالدران','slug' => 'چالدران','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '29','province_id' => '2','active' => '1','title' => 'چایپاره','slug' => 'چایپاره','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '30','province_id' => '2','active' => '1','title' => 'خوی','slug' => 'خوی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '31','province_id' => '2','active' => '1','title' => 'سردشت','slug' => 'سردشت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '32','province_id' => '2','active' => '1','title' => 'سلماس','slug' => 'سلماس','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '33','province_id' => '2','active' => '1','title' => 'شاهین دژ','slug' => 'شاهین_دژ','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '34','province_id' => '2','active' => '1','title' => 'شوط','slug' => 'شوط','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '35','province_id' => '2','active' => '1','title' => 'ماکو','slug' => 'ماکو','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '36','province_id' => '2','active' => '1','title' => 'مهاباد','slug' => 'مهاباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '37','province_id' => '2','active' => '1','title' => 'میاندوآب','slug' => 'میاندوآب','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '38','province_id' => '2','active' => '1','title' => 'نقده','slug' => 'نقده','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '39','province_id' => '3','active' => '1','title' => 'اردبیل','slug' => 'اردبیل','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '40','province_id' => '3','active' => '1','title' => 'اصلاندوز','slug' => 'اصلاندوز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '41','province_id' => '3','active' => '1','title' => 'بیله سوار','slug' => 'بیله_سوار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '42','province_id' => '3','active' => '1','title' => 'پارس آباد','slug' => 'پارس_آباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '43','province_id' => '3','active' => '1','title' => 'خلخال','slug' => 'خلخال','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '44','province_id' => '3','active' => '1','title' => 'سرعین','slug' => 'سرعین','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '45','province_id' => '3','active' => '1','title' => 'کوثر','slug' => 'کوثر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '46','province_id' => '3','active' => '1','title' => 'گرمی','slug' => 'گرمی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '47','province_id' => '3','active' => '1','title' => 'مشگین شهر','slug' => 'مشگین_شهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '48','province_id' => '3','active' => '1','title' => 'نمین','slug' => 'نمین','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '49','province_id' => '3','active' => '1','title' => 'نیر','slug' => 'نیر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '50','province_id' => '4','active' => '1','title' => 'آران وبیدگل','slug' => 'آران_وبیدگل','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '51','province_id' => '4','active' => '1','title' => 'اردستان','slug' => 'اردستان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '52','province_id' => '4','active' => '1','title' => 'اصفهان','slug' => 'اصفهان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '53','province_id' => '4','active' => '1','title' => 'برخوار','slug' => 'برخوار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '54','province_id' => '4','active' => '1','title' => 'بو یین و میاندشت','slug' => 'بو_یین_و_میاندشت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '55','province_id' => '4','active' => '1','title' => 'تیران وکرون','slug' => 'تیران_وکرون','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '56','province_id' => '4','active' => '1','title' => 'چادگان','slug' => 'چادگان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '57','province_id' => '4','active' => '1','title' => 'خمینی شهر','slug' => 'خمینی_شهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '58','province_id' => '4','active' => '1','title' => 'خوانسار','slug' => 'خوانسار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '59','province_id' => '4','active' => '1','title' => 'خور و بیابانک','slug' => 'خور_و_بیابانک','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '60','province_id' => '4','active' => '1','title' => 'دهاقان','slug' => 'دهاقان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '61','province_id' => '4','active' => '1','title' => 'سمیرم','slug' => 'سمیرم','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '62','province_id' => '4','active' => '1','title' => 'شاهین شهرومیمه','slug' => 'شاهین_شهرومیمه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '63','province_id' => '4','active' => '1','title' => 'شهرضا','slug' => 'شهرضا','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '64','province_id' => '4','active' => '1','title' => 'فریدن','slug' => 'فریدن','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '65','province_id' => '4','active' => '1','title' => 'فریدونشهر','slug' => 'فریدونشهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '66','province_id' => '4','active' => '1','title' => 'فلاورجان','slug' => 'فلاورجان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '67','province_id' => '4','active' => '1','title' => 'کاشان','slug' => 'کاشان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '68','province_id' => '4','active' => '1','title' => 'گلپایگان','slug' => 'گلپایگان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '69','province_id' => '4','active' => '1','title' => 'لنجان','slug' => 'لنجان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '70','province_id' => '4','active' => '1','title' => 'مبارکه','slug' => 'مبارکه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '71','province_id' => '4','active' => '1','title' => 'نایین','slug' => 'نایین','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '72','province_id' => '4','active' => '1','title' => 'نجف آباد','slug' => 'نجف_آباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '73','province_id' => '4','active' => '1','title' => 'نطنز','slug' => 'نطنز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '74','province_id' => '5','active' => '1','title' => 'اشتهارد','slug' => 'اشتهارد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '75','province_id' => '5','active' => '1','title' => 'ساوجبلاغ','slug' => 'ساوجبلاغ','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '76','province_id' => '5','active' => '1','title' => 'طالقان','slug' => 'طالقان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '77','province_id' => '5','active' => '1','title' => 'فردیس','slug' => 'فردیس','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '78','province_id' => '5','active' => '1','title' => 'کرج','slug' => 'کرج','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '79','province_id' => '5','active' => '1','title' => 'نظرآباد','slug' => 'نظرآباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '80','province_id' => '6','active' => '1','title' => 'آبدانان','slug' => 'آبدانان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '81','province_id' => '6','active' => '1','title' => 'ایلام','slug' => 'ایلام','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '82','province_id' => '6','active' => '1','title' => 'ایوان','slug' => 'ایوان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '83','province_id' => '6','active' => '1','title' => 'بدره','slug' => 'بدره','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '84','province_id' => '6','active' => '1','title' => 'چرداول','slug' => 'چرداول','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '85','province_id' => '6','active' => '1','title' => 'دره شهر','slug' => 'دره_شهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '86','province_id' => '6','active' => '1','title' => 'دهلران','slug' => 'دهلران','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '87','province_id' => '6','active' => '1','title' => 'سیروان','slug' => 'سیروان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '88','province_id' => '6','active' => '1','title' => 'ملکشاهی','slug' => 'ملکشاهی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '89','province_id' => '6','active' => '1','title' => 'مهران','slug' => 'مهران','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '90','province_id' => '7','active' => '1','title' => 'بوشهر','slug' => 'بوشهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '91','province_id' => '7','active' => '1','title' => 'تنگستان','slug' => 'تنگستان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '92','province_id' => '7','active' => '1','title' => 'جم','slug' => 'جم','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '93','province_id' => '7','active' => '1','title' => 'دشتستان','slug' => 'دشتستان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '94','province_id' => '7','active' => '1','title' => 'دشتی','slug' => 'دشتی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '95','province_id' => '7','active' => '1','title' => 'دیر','slug' => 'دیر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '96','province_id' => '7','active' => '1','title' => 'دیلم','slug' => 'دیلم','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '97','province_id' => '7','active' => '1','title' => 'عسلویه','slug' => 'عسلویه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '98','province_id' => '7','active' => '1','title' => 'کنگان','slug' => 'کنگان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '99','province_id' => '7','active' => '1','title' => 'گناوه','slug' => 'گناوه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '100','province_id' => '8','active' => '1','title' => 'اسلامشهر','slug' => 'اسلامشهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '101','province_id' => '8','active' => '1','title' => 'بهارستان','slug' => 'بهارستان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '102','province_id' => '8','active' => '1','title' => 'پاکدشت','slug' => 'پاکدشت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '103','province_id' => '8','active' => '1','title' => 'پردیس','slug' => 'پردیس','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '104','province_id' => '8','active' => '1','title' => 'پیشوا','slug' => 'پیشوا','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '105','province_id' => '8','active' => '1','title' => 'تهران','slug' => 'تهران','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '106','province_id' => '8','active' => '1','title' => 'دماوند','slug' => 'دماوند','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '107','province_id' => '8','active' => '1','title' => 'ری','slug' => 'ری','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '108','province_id' => '8','active' => '1','title' => 'رباط کریم','slug' => 'رباط_کریم','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '109','province_id' => '8','active' => '1','title' => 'شمیرانات','slug' => 'شمیرانات','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '110','province_id' => '8','active' => '1','title' => 'شهریار','slug' => 'شهریار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '111','province_id' => '8','active' => '1','title' => 'فیروزکوه','slug' => 'فیروزکوه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '112','province_id' => '8','active' => '1','title' => 'قدس','slug' => 'قدس','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '113','province_id' => '8','active' => '1','title' => 'قرچک','slug' => 'قرچک','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '114','province_id' => '8','active' => '1','title' => 'ملارد','slug' => 'ملارد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '115','province_id' => '8','active' => '1','title' => 'ورامین','slug' => 'ورامین','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '116','province_id' => '9','active' => '1','title' => 'اردل','slug' => 'اردل','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '117','province_id' => '9','active' => '1','title' => 'بروجن','slug' => 'بروجن','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '118','province_id' => '9','active' => '1','title' => 'بن','slug' => 'بن','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '119','province_id' => '9','active' => '1','title' => 'خانمیرزا','slug' => 'خانمیرزا','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '120','province_id' => '9','active' => '1','title' => 'سامان','slug' => 'سامان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '121','province_id' => '9','active' => '1','title' => 'شهرکرد','slug' => 'شهرکرد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '122','province_id' => '9','active' => '1','title' => 'فارسان','slug' => 'فارسان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '123','province_id' => '9','active' => '1','title' => 'کوهرنگ','slug' => 'کوهرنگ','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '124','province_id' => '9','active' => '1','title' => 'کیار','slug' => 'کیار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '125','province_id' => '9','active' => '1','title' => 'لردگان','slug' => 'لردگان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '126','province_id' => '10','active' => '1','title' => 'بشرویه','slug' => 'بشرویه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '127','province_id' => '10','active' => '1','title' => 'بیرجند','slug' => 'بیرجند','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '128','province_id' => '10','active' => '1','title' => 'خوسف','slug' => 'خوسف','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '129','province_id' => '10','active' => '1','title' => 'درمیان','slug' => 'درمیان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '130','province_id' => '10','active' => '1','title' => 'زیرکوه','slug' => 'زیرکوه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '131','province_id' => '10','active' => '1','title' => 'سرایان','slug' => 'سرایان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '132','province_id' => '10','active' => '1','title' => 'سربیشه','slug' => 'سربیشه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '133','province_id' => '10','active' => '1','title' => 'طبس','slug' => 'طبس','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '134','province_id' => '10','active' => '1','title' => 'فردوس','slug' => 'فردوس','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '135','province_id' => '10','active' => '1','title' => 'قاینات','slug' => 'قاینات','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '136','province_id' => '10','active' => '1','title' => 'نهبندان','slug' => 'نهبندان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '137','province_id' => '11','active' => '1','title' => 'باخرز','slug' => 'باخرز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '138','province_id' => '11','active' => '1','title' => 'بجستان','slug' => 'بجستان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '139','province_id' => '11','active' => '1','title' => 'بردسکن','slug' => 'بردسکن','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '140','province_id' => '11','active' => '1','title' => 'بینالود','slug' => 'بینالود','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '141','province_id' => '11','active' => '1','title' => 'تایباد','slug' => 'تایباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '142','province_id' => '11','active' => '1','title' => 'تربت جام','slug' => 'تربت_جام','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '143','province_id' => '11','active' => '1','title' => 'تربت حیدریه','slug' => 'تربت_حیدریه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '144','province_id' => '11','active' => '1','title' => 'جغتای','slug' => 'جغتای','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '145','province_id' => '11','active' => '1','title' => 'جوین','slug' => 'جوین','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '146','province_id' => '11','active' => '1','title' => 'چناران','slug' => 'چناران','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '147','province_id' => '11','active' => '1','title' => 'خلیل آباد','slug' => 'خلیل_آباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '148','province_id' => '11','active' => '1','title' => 'خواف','slug' => 'خواف','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '149','province_id' => '11','active' => '1','title' => 'خوشاب','slug' => 'خوشاب','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '150','province_id' => '11','active' => '1','title' => 'داورزن','slug' => 'داورزن','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '151','province_id' => '11','active' => '1','title' => 'درگز','slug' => 'درگز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '152','province_id' => '11','active' => '1','title' => 'رشتخوار','slug' => 'رشتخوار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '153','province_id' => '11','active' => '1','title' => 'زاوه','slug' => 'زاوه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '154','province_id' => '11','active' => '1','title' => 'سبزوار','slug' => 'سبزوار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '155','province_id' => '11','active' => '1','title' => 'سرخس','slug' => 'سرخس','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '156','province_id' => '11','active' => '1','title' => 'صالح آباد','slug' => 'صالح_آباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '157','province_id' => '11','active' => '1','title' => 'فریمان','slug' => 'فریمان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '158','province_id' => '11','active' => '1','title' => 'فیروزه','slug' => 'فیروزه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '159','province_id' => '11','active' => '1','title' => 'قوچان','slug' => 'قوچان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '160','province_id' => '11','active' => '1','title' => 'کاشمر','slug' => 'کاشمر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '161','province_id' => '11','active' => '1','title' => 'کلات','slug' => 'کلات','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '162','province_id' => '11','active' => '1','title' => 'گناباد','slug' => 'گناباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '163','province_id' => '11','active' => '1','title' => 'مشهد','slug' => 'مشهد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '164','province_id' => '11','active' => '1','title' => 'مه ولات','slug' => 'مه_ولات','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '165','province_id' => '11','active' => '1','title' => 'نیشابور','slug' => 'نیشابور','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '166','province_id' => '12','active' => '1','title' => 'اسفراین','slug' => 'اسفراین','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '167','province_id' => '12','active' => '1','title' => 'بجنورد','slug' => 'بجنورد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '168','province_id' => '12','active' => '1','title' => 'جاجرم','slug' => 'جاجرم','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '169','province_id' => '12','active' => '1','title' => 'راز و جرگلان','slug' => 'راز_و_جرگلان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '170','province_id' => '12','active' => '1','title' => 'شیروان','slug' => 'شیروان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '171','province_id' => '12','active' => '1','title' => 'فاروج','slug' => 'فاروج','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '172','province_id' => '12','active' => '1','title' => 'گرمه','slug' => 'گرمه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '173','province_id' => '12','active' => '1','title' => 'مانه وسملقان','slug' => 'مانه_وسملقان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '174','province_id' => '13','active' => '1','title' => 'آبادان','slug' => 'آبادان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '175','province_id' => '13','active' => '1','title' => 'آغاجاری','slug' => 'آغاجاری','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '176','province_id' => '13','active' => '1','title' => 'امیدیه','slug' => 'امیدیه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '177','province_id' => '13','active' => '1','title' => 'اندیکا','slug' => 'اندیکا','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '178','province_id' => '13','active' => '1','title' => 'اندیمشک','slug' => 'اندیمشک','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '179','province_id' => '13','active' => '1','title' => 'اهواز','slug' => 'اهواز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '180','province_id' => '13','active' => '1','title' => 'ایذه','slug' => 'ایذه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '181','province_id' => '13','active' => '1','title' => 'باغ ملک','slug' => 'باغ_ملک','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '182','province_id' => '13','active' => '1','title' => 'باوی','slug' => 'باوی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '183','province_id' => '13','active' => '1','title' => 'بندرماهشهر','slug' => 'بندرماهشهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '184','province_id' => '13','active' => '1','title' => 'بهبهان','slug' => 'بهبهان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '185','province_id' => '13','active' => '1','title' => 'حمیدیه','slug' => 'حمیدیه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '186','province_id' => '13','active' => '1','title' => 'خرمشهر','slug' => 'خرمشهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '187','province_id' => '13','active' => '1','title' => 'دزفول','slug' => 'دزفول','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '188','province_id' => '13','active' => '1','title' => 'دشت آزادگان','slug' => 'دشت_آزادگان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '189','province_id' => '13','active' => '1','title' => 'رامشیر','slug' => 'رامشیر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '190','province_id' => '13','active' => '1','title' => 'رامهرمز','slug' => 'رامهرمز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '191','province_id' => '13','active' => '1','title' => 'شادگان','slug' => 'شادگان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '192','province_id' => '13','active' => '1','title' => 'شوش','slug' => 'شوش','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '193','province_id' => '13','active' => '1','title' => 'شوشتر','slug' => 'شوشتر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '194','province_id' => '13','active' => '1','title' => 'کارون','slug' => 'کارون','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '195','province_id' => '13','active' => '1','title' => 'گتوند','slug' => 'گتوند','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '196','province_id' => '13','active' => '1','title' => 'لالی','slug' => 'لالی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '197','province_id' => '13','active' => '1','title' => 'مسجدسلیمان','slug' => 'مسجدسلیمان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '198','province_id' => '13','active' => '1','title' => 'هفتکل','slug' => 'هفتکل','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '199','province_id' => '13','active' => '1','title' => 'هندیجان','slug' => 'هندیجان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '200','province_id' => '13','active' => '1','title' => 'هویزه','slug' => 'هویزه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '201','province_id' => '14','active' => '1','title' => 'ابهر','slug' => 'ابهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '202','province_id' => '14','active' => '1','title' => 'ایجرود','slug' => 'ایجرود','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '203','province_id' => '14','active' => '1','title' => 'خدابنده','slug' => 'خدابنده','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '204','province_id' => '14','active' => '1','title' => 'خرمدره','slug' => 'خرمدره','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '205','province_id' => '14','active' => '1','title' => 'زنجان','slug' => 'زنجان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '206','province_id' => '14','active' => '1','title' => 'سلطانیه','slug' => 'سلطانیه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '207','province_id' => '14','active' => '1','title' => 'طارم','slug' => 'طارم','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '208','province_id' => '14','active' => '1','title' => 'ماهنشان','slug' => 'ماهنشان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '209','province_id' => '15','active' => '1','title' => 'آرادان','slug' => 'آرادان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '210','province_id' => '15','active' => '1','title' => 'دامغان','slug' => 'دامغان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '211','province_id' => '15','active' => '1','title' => 'سرخه','slug' => 'سرخه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '212','province_id' => '15','active' => '1','title' => 'سمنان','slug' => 'سمنان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '213','province_id' => '15','active' => '1','title' => 'شاهرود','slug' => 'شاهرود','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '214','province_id' => '15','active' => '1','title' => 'گرمسار','slug' => 'گرمسار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '215','province_id' => '15','active' => '1','title' => 'مهدی شهر','slug' => 'مهدی_شهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '216','province_id' => '15','active' => '1','title' => 'میامی','slug' => 'میامی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '217','province_id' => '16','active' => '1','title' => 'ایرانشهر','slug' => 'ایرانشهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '218','province_id' => '16','active' => '1','title' => 'بمپور','slug' => 'بمپور','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '219','province_id' => '16','active' => '1','title' => 'چابهار','slug' => 'چابهار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '220','province_id' => '16','active' => '1','title' => 'خاش','slug' => 'خاش','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '221','province_id' => '16','active' => '1','title' => 'دلگان','slug' => 'دلگان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '222','province_id' => '16','active' => '1','title' => 'زابل','slug' => 'زابل','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '223','province_id' => '16','active' => '1','title' => 'زاهدان','slug' => 'زاهدان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '224','province_id' => '16','active' => '1','title' => 'زهک','slug' => 'زهک','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '225','province_id' => '16','active' => '1','title' => 'سراوان','slug' => 'سراوان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '226','province_id' => '16','active' => '1','title' => 'سرباز','slug' => 'سرباز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '227','province_id' => '16','active' => '1','title' => 'سیب و سوران','slug' => 'سیب_و_سوران','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '228','province_id' => '16','active' => '1','title' => 'فنوج','slug' => 'فنوج','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '229','province_id' => '16','active' => '1','title' => 'قصرقند','slug' => 'قصرقند','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '230','province_id' => '16','active' => '1','title' => 'کنارک','slug' => 'کنارک','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '231','province_id' => '16','active' => '1','title' => 'مهرستان','slug' => 'مهرستان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '232','province_id' => '16','active' => '1','title' => 'میرجاوه','slug' => 'میرجاوه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '233','province_id' => '16','active' => '1','title' => 'نیک شهر','slug' => 'نیک_شهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '234','province_id' => '16','active' => '1','title' => 'نیمروز','slug' => 'نیمروز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '235','province_id' => '16','active' => '1','title' => 'هامون','slug' => 'هامون','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '236','province_id' => '16','active' => '1','title' => 'هیرمند','slug' => 'هیرمند','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '237','province_id' => '17','active' => '1','title' => 'آباده','slug' => 'آباده','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '238','province_id' => '17','active' => '1','title' => 'ارسنجان','slug' => 'ارسنجان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '239','province_id' => '17','active' => '1','title' => 'استهبان','slug' => 'استهبان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '240','province_id' => '17','active' => '1','title' => 'اقلید','slug' => 'اقلید','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '241','province_id' => '17','active' => '1','title' => 'بوانات','slug' => 'بوانات','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '242','province_id' => '17','active' => '1','title' => 'پاسارگاد','slug' => 'پاسارگاد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '243','province_id' => '17','active' => '1','title' => 'جهرم','slug' => 'جهرم','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '244','province_id' => '17','active' => '1','title' => 'خرامه','slug' => 'خرامه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '245','province_id' => '17','active' => '1','title' => 'خرم بید','slug' => 'خرم_بید','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '246','province_id' => '17','active' => '1','title' => 'خنج','slug' => 'خنج','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '247','province_id' => '17','active' => '1','title' => 'داراب','slug' => 'داراب','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '248','province_id' => '17','active' => '1','title' => 'رستم','slug' => 'رستم','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '249','province_id' => '17','active' => '1','title' => 'زرین دشت','slug' => 'زرین_دشت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '250','province_id' => '17','active' => '1','title' => 'سپیدان','slug' => 'سپیدان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '251','province_id' => '17','active' => '1','title' => 'سروستان','slug' => 'سروستان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '252','province_id' => '17','active' => '1','title' => 'شیراز','slug' => 'شیراز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '253','province_id' => '17','active' => '1','title' => 'فراشبند','slug' => 'فراشبند','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '254','province_id' => '17','active' => '1','title' => 'فسا','slug' => 'فسا','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '255','province_id' => '17','active' => '1','title' => 'فیروزآباد','slug' => 'فیروزآباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '256','province_id' => '17','active' => '1','title' => 'قیروکارزین','slug' => 'قیروکارزین','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '257','province_id' => '17','active' => '1','title' => 'کازرون','slug' => 'کازرون','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '258','province_id' => '17','active' => '1','title' => 'کوار','slug' => 'کوار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '259','province_id' => '17','active' => '1','title' => 'گراش','slug' => 'گراش','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '260','province_id' => '17','active' => '1','title' => 'لارستان','slug' => 'لارستان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '261','province_id' => '17','active' => '1','title' => 'لامرد','slug' => 'لامرد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '262','province_id' => '17','active' => '1','title' => 'مرودشت','slug' => 'مرودشت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '263','province_id' => '17','active' => '1','title' => 'ممسنی','slug' => 'ممسنی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '264','province_id' => '17','active' => '1','title' => 'مهر','slug' => 'مهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '265','province_id' => '17','active' => '1','title' => 'نی ریز','slug' => 'نی_ریز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '266','province_id' => '18','active' => '1','title' => 'آبیک','slug' => 'آبیک','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '267','province_id' => '18','active' => '1','title' => 'آوج','slug' => 'آوج','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '268','province_id' => '18','active' => '1','title' => 'البرز','slug' => 'البرز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '269','province_id' => '18','active' => '1','title' => 'بویین زهرا','slug' => 'بویین_زهرا','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '270','province_id' => '18','active' => '1','title' => 'تاکستان','slug' => 'تاکستان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '271','province_id' => '18','active' => '1','title' => 'قزوین','slug' => 'قزوین','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '272','province_id' => '19','active' => '1','title' => 'قم','slug' => 'قم','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '273','province_id' => '20','active' => '1','title' => 'بانه','slug' => 'بانه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '274','province_id' => '20','active' => '1','title' => 'بیجار','slug' => 'بیجار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '275','province_id' => '20','active' => '1','title' => 'دهگلان','slug' => 'دهگلان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '276','province_id' => '20','active' => '1','title' => 'دیواندره','slug' => 'دیواندره','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '277','province_id' => '20','active' => '1','title' => 'سروآباد','slug' => 'سروآباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '278','province_id' => '20','active' => '1','title' => 'سقز','slug' => 'سقز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '279','province_id' => '20','active' => '1','title' => 'سنندج','slug' => 'سنندج','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '280','province_id' => '20','active' => '1','title' => 'قروه','slug' => 'قروه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '281','province_id' => '20','active' => '1','title' => 'کامیاران','slug' => 'کامیاران','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '282','province_id' => '20','active' => '1','title' => 'مریوان','slug' => 'مریوان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '283','province_id' => '21','active' => '1','title' => 'ارزوییه','slug' => 'ارزوییه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '284','province_id' => '21','active' => '1','title' => 'انار','slug' => 'انار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '285','province_id' => '21','active' => '1','title' => 'بافت','slug' => 'بافت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '286','province_id' => '21','active' => '1','title' => 'بردسیر','slug' => 'بردسیر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '287','province_id' => '21','active' => '1','title' => 'بم','slug' => 'بم','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '288','province_id' => '21','active' => '1','title' => 'جیرفت','slug' => 'جیرفت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '289','province_id' => '21','active' => '1','title' => 'رابر','slug' => 'رابر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '290','province_id' => '21','active' => '1','title' => 'راور','slug' => 'راور','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '291','province_id' => '21','active' => '1','title' => 'رفسنجان','slug' => 'رفسنجان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '292','province_id' => '21','active' => '1','title' => 'رودبارجنوب','slug' => 'رودبارجنوب','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '293','province_id' => '21','active' => '1','title' => 'ریگان','slug' => 'ریگان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '294','province_id' => '21','active' => '1','title' => 'زرند','slug' => 'زرند','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '295','province_id' => '21','active' => '1','title' => 'سیرجان','slug' => 'سیرجان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '296','province_id' => '21','active' => '1','title' => 'شهربابک','slug' => 'شهربابک','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '297','province_id' => '21','active' => '1','title' => 'عنبرآباد','slug' => 'عنبرآباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '298','province_id' => '21','active' => '1','title' => 'فاریاب','slug' => 'فاریاب','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '299','province_id' => '21','active' => '1','title' => 'فهرج','slug' => 'فهرج','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '300','province_id' => '21','active' => '1','title' => 'قلعه گنج','slug' => 'قلعه_گنج','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '301','province_id' => '21','active' => '1','title' => 'کرمان','slug' => 'کرمان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '302','province_id' => '21','active' => '1','title' => 'کوهبنان','slug' => 'کوهبنان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '303','province_id' => '21','active' => '1','title' => 'کهنوج','slug' => 'کهنوج','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '304','province_id' => '21','active' => '1','title' => 'منوجان','slug' => 'منوجان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '305','province_id' => '21','active' => '1','title' => 'نرماشیر','slug' => 'نرماشیر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '306','province_id' => '22','active' => '1','title' => 'اسلام آبادغرب','slug' => 'اسلام_آبادغرب','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '307','province_id' => '22','active' => '1','title' => 'پاوه','slug' => 'پاوه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '308','province_id' => '22','active' => '1','title' => 'ثلاث باباجانی','slug' => 'ثلاث_باباجانی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '309','province_id' => '22','active' => '1','title' => 'جوانرود','slug' => 'جوانرود','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '310','province_id' => '22','active' => '1','title' => 'دالاهو','slug' => 'دالاهو','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '311','province_id' => '22','active' => '1','title' => 'روانسر','slug' => 'روانسر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '312','province_id' => '22','active' => '1','title' => 'سرپل ذهاب','slug' => 'سرپل_ذهاب','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '313','province_id' => '22','active' => '1','title' => 'سنقر','slug' => 'سنقر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '314','province_id' => '22','active' => '1','title' => 'صحنه','slug' => 'صحنه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '315','province_id' => '22','active' => '1','title' => 'قصرشیرین','slug' => 'قصرشیرین','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '316','province_id' => '22','active' => '1','title' => 'کرمانشاه','slug' => 'کرمانشاه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '317','province_id' => '22','active' => '1','title' => 'کنگاور','slug' => 'کنگاور','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '318','province_id' => '22','active' => '1','title' => 'گیلانغرب','slug' => 'گیلانغرب','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '319','province_id' => '22','active' => '1','title' => 'هرسین','slug' => 'هرسین','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '320','province_id' => '23','active' => '1','title' => 'باشت','slug' => 'باشت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '321','province_id' => '23','active' => '1','title' => 'بویراحمد','slug' => 'بویراحمد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '322','province_id' => '23','active' => '1','title' => 'بهمیی','slug' => 'بهمیی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '323','province_id' => '23','active' => '1','title' => 'چرام','slug' => 'چرام','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '324','province_id' => '23','active' => '1','title' => 'دنا','slug' => 'دنا','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '325','province_id' => '23','active' => '1','title' => 'کهگیلویه','slug' => 'کهگیلویه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '326','province_id' => '23','active' => '1','title' => 'گچساران','slug' => 'گچساران','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '327','province_id' => '23','active' => '1','title' => 'لنده','slug' => 'لنده','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '328','province_id' => '24','active' => '1','title' => 'آزادشهر','slug' => 'آزادشهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '329','province_id' => '24','active' => '1','title' => 'آق قلا','slug' => 'آق_قلا','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '330','province_id' => '24','active' => '1','title' => 'بندرگز','slug' => 'بندرگز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '331','province_id' => '24','active' => '1','title' => 'ترکمن','slug' => 'ترکمن','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '332','province_id' => '24','active' => '1','title' => 'رامیان','slug' => 'رامیان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '333','province_id' => '24','active' => '1','title' => 'علی آباد','slug' => 'علی_آباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '334','province_id' => '24','active' => '1','title' => 'کردکوی','slug' => 'کردکوی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '335','province_id' => '24','active' => '1','title' => 'کلاله','slug' => 'کلاله','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '336','province_id' => '24','active' => '1','title' => 'گالیکش','slug' => 'گالیکش','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '337','province_id' => '24','active' => '1','title' => 'گرگان','slug' => 'گرگان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '338','province_id' => '24','active' => '1','title' => 'گمیشان','slug' => 'گمیشان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '339','province_id' => '24','active' => '1','title' => 'گنبدکاووس','slug' => 'گنبدکاووس','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '340','province_id' => '24','active' => '1','title' => 'مراوه تپه','slug' => 'مراوه_تپه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '341','province_id' => '24','active' => '1','title' => 'مینودشت','slug' => 'مینودشت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '342','province_id' => '25','active' => '1','title' => 'آستارا','slug' => 'آستارا','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '343','province_id' => '25','active' => '1','title' => 'آستانه اشرفیه','slug' => 'آستانه_اشرفیه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '344','province_id' => '25','active' => '1','title' => 'املش','slug' => 'املش','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '345','province_id' => '25','active' => '1','title' => 'بندرانزلی','slug' => 'بندرانزلی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '346','province_id' => '25','active' => '1','title' => 'رشت','slug' => 'رشت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '347','province_id' => '25','active' => '1','title' => 'رضوانشهر','slug' => 'رضوانشهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '348','province_id' => '25','active' => '1','title' => 'رودبار','slug' => 'رودبار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '349','province_id' => '25','active' => '1','title' => 'رودسر','slug' => 'رودسر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '350','province_id' => '25','active' => '1','title' => 'سیاهکل','slug' => 'سیاهکل','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '351','province_id' => '25','active' => '1','title' => 'شفت','slug' => 'شفت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '352','province_id' => '25','active' => '1','title' => 'صومعه سرا','slug' => 'صومعه_سرا','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '353','province_id' => '25','active' => '1','title' => 'طوالش','slug' => 'طوالش','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '354','province_id' => '25','active' => '1','title' => 'فومن','slug' => 'فومن','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '355','province_id' => '25','active' => '1','title' => 'لاهیجان','slug' => 'لاهیجان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '356','province_id' => '25','active' => '1','title' => 'لنگرود','slug' => 'لنگرود','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '357','province_id' => '25','active' => '1','title' => 'ماسال','slug' => 'ماسال','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '358','province_id' => '26','active' => '1','title' => 'ازنا','slug' => 'ازنا','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '359','province_id' => '26','active' => '1','title' => 'الیگودرز','slug' => 'الیگودرز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '360','province_id' => '26','active' => '1','title' => 'بروجرد','slug' => 'بروجرد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '361','province_id' => '26','active' => '1','title' => 'پلدختر','slug' => 'پلدختر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '362','province_id' => '26','active' => '1','title' => 'چگنی','slug' => 'چگنی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '363','province_id' => '26','active' => '1','title' => 'خرم آباد','slug' => 'خرم_آباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '364','province_id' => '26','active' => '1','title' => 'دلفان','slug' => 'دلفان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '365','province_id' => '26','active' => '1','title' => 'دورود','slug' => 'دورود','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '366','province_id' => '26','active' => '1','title' => 'رومشکان','slug' => 'رومشکان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '367','province_id' => '26','active' => '1','title' => 'سلسله','slug' => 'سلسله','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '368','province_id' => '26','active' => '1','title' => 'کوهدشت','slug' => 'کوهدشت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '369','province_id' => '27','active' => '1','title' => 'آمل','slug' => 'آمل','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '370','province_id' => '27','active' => '1','title' => 'بابل','slug' => 'بابل','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '371','province_id' => '27','active' => '1','title' => 'بابلسر','slug' => 'بابلسر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '372','province_id' => '27','active' => '1','title' => 'بهشهر','slug' => 'بهشهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '373','province_id' => '27','active' => '1','title' => 'تنکابن','slug' => 'تنکابن','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '374','province_id' => '27','active' => '1','title' => 'جویبار','slug' => 'جویبار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '375','province_id' => '27','active' => '1','title' => 'چالوس','slug' => 'چالوس','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '376','province_id' => '27','active' => '1','title' => 'رامسر','slug' => 'رامسر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '377','province_id' => '27','active' => '1','title' => 'ساری','slug' => 'ساری','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '378','province_id' => '27','active' => '1','title' => 'سوادکوه','slug' => 'سوادکوه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '379','province_id' => '27','active' => '1','title' => 'سوادکوه شمالی','slug' => 'سوادکوه_شمالی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '380','province_id' => '27','active' => '1','title' => 'سیمرغ','slug' => 'سیمرغ','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '381','province_id' => '27','active' => '1','title' => 'عباس آباد','slug' => 'عباس_آباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '382','province_id' => '27','active' => '1','title' => 'فریدونکنار','slug' => 'فریدونکنار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '383','province_id' => '27','active' => '1','title' => 'قایم شهر','slug' => 'قایم_شهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '384','province_id' => '27','active' => '1','title' => 'کلاردشت','slug' => 'کلاردشت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '385','province_id' => '27','active' => '1','title' => 'گلوگاه','slug' => 'گلوگاه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '386','province_id' => '27','active' => '1','title' => 'محمودآباد','slug' => 'محمودآباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '387','province_id' => '27','active' => '1','title' => 'میاندورود','slug' => 'میاندورود','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '388','province_id' => '27','active' => '1','title' => 'نکا','slug' => 'نکا','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '389','province_id' => '27','active' => '1','title' => 'نور','slug' => 'نور','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '390','province_id' => '27','active' => '1','title' => 'نوشهر','slug' => 'نوشهر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '391','province_id' => '28','active' => '1','title' => 'آشتیان','slug' => 'آشتیان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '392','province_id' => '28','active' => '1','title' => 'اراک','slug' => 'اراک','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '393','province_id' => '28','active' => '1','title' => 'تفرش','slug' => 'تفرش','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '394','province_id' => '28','active' => '1','title' => 'خمین','slug' => 'خمین','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '395','province_id' => '28','active' => '1','title' => 'خنداب','slug' => 'خنداب','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '396','province_id' => '28','active' => '1','title' => 'دلیجان','slug' => 'دلیجان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '397','province_id' => '28','active' => '1','title' => 'زرندیه','slug' => 'زرندیه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '398','province_id' => '28','active' => '1','title' => 'ساوه','slug' => 'ساوه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '399','province_id' => '28','active' => '1','title' => 'شازند','slug' => 'شازند','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '400','province_id' => '28','active' => '1','title' => 'فراهان','slug' => 'فراهان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '401','province_id' => '28','active' => '1','title' => 'کمیجان','slug' => 'کمیجان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '402','province_id' => '28','active' => '1','title' => 'محلات','slug' => 'محلات','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '403','province_id' => '29','active' => '1','title' => 'ابوموسی','slug' => 'ابوموسی','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '404','province_id' => '29','active' => '1','title' => 'بستک','slug' => 'بستک','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '405','province_id' => '29','active' => '1','title' => 'بشاگرد','slug' => 'بشاگرد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '406','province_id' => '29','active' => '1','title' => 'بندرعباس','slug' => 'بندرعباس','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '407','province_id' => '29','active' => '1','title' => 'بندرلنگه','slug' => 'بندرلنگه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '408','province_id' => '29','active' => '1','title' => 'پارسیان','slug' => 'پارسیان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '409','province_id' => '29','active' => '1','title' => 'جاسک','slug' => 'جاسک','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '410','province_id' => '29','active' => '1','title' => 'حاجی اباد','slug' => 'حاجی_اباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '411','province_id' => '29','active' => '1','title' => 'خمیر','slug' => 'خمیر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '412','province_id' => '29','active' => '1','title' => 'رودان','slug' => 'رودان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '413','province_id' => '29','active' => '1','title' => 'سیریک','slug' => 'سیریک','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '414','province_id' => '29','active' => '1','title' => 'قشم','slug' => 'قشم','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '415','province_id' => '29','active' => '1','title' => 'میناب','slug' => 'میناب','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '416','province_id' => '30','active' => '1','title' => 'اسدآباد','slug' => 'اسدآباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '417','province_id' => '30','active' => '1','title' => 'بهار','slug' => 'بهار','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '418','province_id' => '30','active' => '1','title' => 'تویسرکان','slug' => 'تویسرکان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '419','province_id' => '30','active' => '1','title' => 'رزن','slug' => 'رزن','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '420','province_id' => '30','active' => '1','title' => 'فامنین','slug' => 'فامنین','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '421','province_id' => '30','active' => '1','title' => 'کبودرآهنگ','slug' => 'کبودرآهنگ','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '422','province_id' => '30','active' => '1','title' => 'ملایر','slug' => 'ملایر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '423','province_id' => '30','active' => '1','title' => 'نهاوند','slug' => 'نهاوند','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '424','province_id' => '30','active' => '1','title' => 'همدان','slug' => 'همدان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '425','province_id' => '31','active' => '1','title' => 'ابرکوه','slug' => 'ابرکوه','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '426','province_id' => '31','active' => '1','title' => 'اردکان','slug' => 'اردکان','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '427','province_id' => '31','active' => '1','title' => 'اشکذر','slug' => 'اشکذر','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '428','province_id' => '31','active' => '1','title' => 'بافق','slug' => 'بافق','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '429','province_id' => '31','active' => '1','title' => 'بهاباد','slug' => 'بهاباد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '430','province_id' => '31','active' => '1','title' => 'تفت','slug' => 'تفت','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '431','province_id' => '31','active' => '1','title' => 'خاتم','slug' => 'خاتم','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '432','province_id' => '31','active' => '1','title' => 'مهریز','slug' => 'مهریز','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '433','province_id' => '31','active' => '1','title' => 'میبد','slug' => 'میبد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
  array('id' => '434','province_id' => '31','active' => '1','title' => 'یزد','slug' => 'یزد','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL)
);
